/*
 *  UCF COP3330 Summer 2021 Assignment 4 Solution
 *  Copyright 2021 Jose Valencia
 */

@startuml
'https://plantuml.com/class-diagram

class TodoList {

    + main()
    + start()

}

class TodoListController {

    AllLists lists
    ObservableList listOfLists
    ObservableList listOfTasks

    - ListView<String> mainListView
    - ListView<String> taskListView

    - TextField newListName
    - TextField editListName
    - TextField newTaskName
    - TextField editTaskName

    - DatePicker addDatePicker
    - DatePicker editTaskDatePicker

    - Button addListBtn
    - Button addTaskBtn
    - Button editListBtn
    - Button editTaskBtn
    - Button removeListBtn
    - Button removeTaskBtn
    - Button markAsCompletedBtn
    - Button viewAllTasksBtn
    - Button viewCompletedBtn
    - Button viewNotCompletedBtn
    - Button sortByDateBtn
    - Button exportSelectedBtn
    - Button importListBtn

    + initialize(URL url, ResourceBundle rb)

    - updateTaskListView()
    - addListBtnClicked(Event e)
    - addTaskBtnClicked(Event e)
    - editListBtnClicked(Event e)
    - editTaskBtnClicked(Event e)
    - removeListBtnClicked(Event e)
    - removeTaskBtnClicked(Event e)
    - markAsCompletedBtnClicked(Event e)
    - viewAllTasksBtnClicked(Event e)
    - viewCompletedBtnClicked(Event e)
    - viewNotCompletedBtnClicked(Event e)
    - exportSelectedBtnClicked(Event e)
    - importListBtnClicked(Event e)
    - sortByDateBtnClicked(Event e)
}

class AllLists {

    ArrayList<List> listsInProgram

    + AllLists()

    + addList(List list)
    + removeList(String list)
    + editList(String list, String name)
    + importList(File file)
    + exportList(File file, List list)


}

class List {

    String name
    ArrayList<Tasks> tasks

    + List(String name)

    + setName(String name)
    + getName()
    + getTasks()

    + addTask(Task task)
    + editTask(String task, String name, String date)
    + removeTask(String task)
    + markTaskCompleted(String task, Boolean completed)
    + showCompleteTasks()
    + showIncompleteTasks()
    + showAllTasks()
    + sortByDate()

    + toString()


}

class Task {

    String desc
    String date
    Boolean completed

    + Task(String desc, String date, Boolean completed)

    + setDesc(String desc)
    + setDate(String date)
    + setCompleted(Boolean completed)
    + getDesc()
    + getDate()
    + getCompleted()

    + toString()


}

javafx.Initializable <|--- TodoListController
javafx.Application <|-- TodoList
TodoList -- TodoListController
TodoListController *-> AllLists
AllLists *--> List
List *--> Task


@enduml